//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertySearch
    {
        public int id { get; set; }
        public string location { get; set; }
        public string type { get; set; }
        public int price { get; set; }
        public string path { get; set; }
        public string pricerange { get; set; }
    }
}
